module.exports = [
  "A Happy DreamHost Customer",
  "Domain Privacy Protector Ltd",
  "Domains By Proxy, LLC",
  "Knock Knock WHOIS Not There",
  "Knock Knock WHOIS Not There, LLC",
  "Perfect Privacy",
  "PERFECT PRIVACY",
  "PERFECT PRIVACY, LLC",
  "Private Registrant",
  "Private Registration",
  "Private Whois",
  "Tigher chap private limited",
  "WHOISGUARD PROTECTED",
  "WHOISGUARD, INC.",
  "Whois Privacy Corp.",
  "Whois Privacy",
  "YoHOST.ORG Privacy Protection",
  "www.PRIVACY.cc",
  "Privacy.CC",
  "YoHOST.ORG Privacy Protection",
]
